---
- name: deploy EAP
  hosts: eap1.rhdemo.local

  tasks:

  - name: add /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.3.222  itehost.example.com   

  - name: copy eap file from server 
    synchronize: 
      mode: pull
      src=/home/ite/a.sh
      dest=/home/redhat/
    delegate_to: ansible