---
- name: deploy EAP
  hosts: eap1.rhdemo.local

  tasks:

  - name: add /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.3.222  itehost.example.com   

  - name: add eap1 to /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: 'eap.rhdemo.local'
      line: '192.168.3.225  eap1.rhdemo.local  eap'

  - name: copy eap file from server 
    synchronize: 
      src: /home/redhat/
      dest: rsync:/home/redhat/a.sh
    delegate_to: itehost.example.com