---
- name: deploy EAP
  hosts: eap1.rhdemo.local

  tasks:

  - name: add /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        192.168.3.222  itehost.example.com   

  - name: add eap1 to /etc/hosts
    lineinfile:
      path: /etc/hosts
      regexp: 'eap.rhdemo.local'
      line: '192.168.3.225  eap1.rhdemo.local  eap'

  - name: copy jboss binary file
    synchronize:
      src: /home/redhat/jboss-eap-7.4.0.zip
      dest: /home/redhat/
    delegate_to: itehost.example.com

  - name: Extract jboss binary file
    unarchive:
      src: /home/redhat/jboss-eap-7.4.0.zip
      dest: /home/redhat/
      remote_src: yes

  - name: copy jdk binary file
    synchronize:
      src: /home/redhat/java-11-openjdk-11.0.9.11-1.portable.jdk.el.x86_64.tar.xz
      dest: /home/redhat/
    delegate_to: itehost.example.com

  - name: Extract jdk binary file
    unarchive:
      src: /home/redhat/java-11-openjdk-11.0.9.11-1.portable.jdk.el.x86_64.tar.xz
      dest: /home/redhat/
      remote_src: yes





