---
- name: Check the Uptime of the servers
  hosts: eap1.rhdemo.local
  connection: local
  tasks:
  - name: Waits for port 22 of any IP to close active connections, don't start checking for 10 seconds
    wait_for:
      timeout: 1
    delegate_to: localhost

  - name: add /etc/hosts
    blockinfile:
      path: /etc/hosts
      block: |
        {{ item.ip }} {{ item.name }}
      marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    loop:
      - { name: itehost.example.com, ip: 192.168.3.222 }