---
- name: Check the Uptime of the servers
  hosts: ansible
  connection: local
  tasks:
  - name: Waits for port 22 of any IP to close active connections, don't start checking for 10 seconds
    wait_for:
      timeout: 40
    delegate_to: localhost