---
- name: start jboss and deploy war file
  hosts: eap1.rhdemo.local

  task: 

  - name: add admin user
    shell: '/home/redhat/jboss-eap-7.4/bin/add-user.sh admin r3dh4t1!'

  - name: run standalone.sh
    shell: nohup /home/redhat/jboss-eap-7.4/bin/standalone.sh &

  - name: deploy war file
    synchronize:
      src: /home/redhat/verify-cluster.war
      dest: /home/redhat/jboss-eap-7.4/standalone/deployments/
    delegate_to: itehost.example.com





  

