---
- name: tranfser file
  hosts: eap1.rhdemo.local

  tasks:

  - name: Extract jboss binary file
    unarchive:
      src: /home/redhat/jboss-eap-7.4.0.zip
      dest: /home/redhat/
      remote_src: yes
