---
- name: tranfser file
  hosts: eap1.rhdemo.local

  tasks:
  - name: Extract jboss binary file
    unarchive:
      src: /home/redhat/jboss-eap-7.4.0.zip
      dest: /home/redhat/
      remote_src: yes

  - name: run standalone.sh
    shell: '/home/redhat/jboss-eap-7.4/bin/add-user.sh admin r3dh4t1!'

  - name: run standalone.sh
    shell: nohup /home/redhat/jboss-eap-7.4/bin/standalone.sh &

  - name: copy war file
    synchronize:
      src: /home/redhat/verify-cluster.war
      dest: /home/redhat/jboss-eap-7.4/standalone/deployments/
    delegate_to: itehost.example.com





  

